# ===================================
#  Form Field Definitions
# ===================================

fields:
    id:
        label: ID
        disabled: true
    task_name:
        label: Task Name
    wgrid_task_id:
        label: WGrid Task ID
        span: auto
    notion_block_id:
        label: Notion Block ID
        span: auto
