# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Task

# Model Form Field configuration
form: $/wezeo/tasks/models/task/fields.yaml

# Model Class name
modelClass: Wezeo\Tasks\Models\Task

# Default redirect location
defaultRedirect: wezeo/tasks/tasks

# Create page
create:
    title: backend::lang.form.create_title
    redirect: wezeo/tasks/tasks/update/:id
    redirectClose: wezeo/tasks/tasks

# Update page
update:
    title: backend::lang.form.update_title
    redirect: wezeo/tasks/tasks
    redirectClose: wezeo/tasks/tasks

# Preview page
preview:
    title: backend::lang.form.preview_title
